# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: b7a1d661694a1a526999fd5fed3bd89b02b8ffe1dd824b05986bdd818c30761355c210a9ff35d7c33674da483cb1220c0a1e23effd5060c3ed41bc79e61337bd
  facebook_app_id: <%= ENV["APP_ID"] %>
  facebook_app_secret: <%= ENV["APP_SECRET"] %>

test:
  secret_key_base: 1a93e624c678c8976aab8afab15ad699535d4276374695a50f70f29d3d347680d2382bfbb362c883d38116c398fa09fb731733bd2092a2ec947d25be3dc752fa


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["APP_ID"] %>
  facebook_app_secret: <%= ENV["APP_SECRET"] %>
